apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app
  labels:
    app: 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: aamirdockerr/python-flask-app:latest
        ports:
        - containerPort: 5000

